language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update && composer install
  - tests/travis/php_setup.sh

script:
  - mkdir -p build/logs
  - ./run_tests.sh

after_script:
  - php vendor/bin/coveralls

services:
  - memcached
  - redis-server
